### ISSUE TITLE
No module name 'tablib'

### ISSUE THREAD

**Issue by Lucasbus** [arungeorge101/myRobinhoodData#1]
File "./rhDataAnalyzer.py", line 5, in <module>
    import tablib
ModuleNotFoundError: No module named 'tablib'

**Comment by arungeorge101** [comment]
@Lucasbus The error basically means that you dont have the dependency installed. Did you run step 8 mentioned in the readme? 

"Now open terminal and browse to the same folder and run **pip install -r requirements.txt** - this is to install all the dependencies for the application"
