### ISSUE TITLE
.xls file creation

### ISSUE THREAD

**Issue by BerkhanEminsoy** [arungeorge101/myRobinhoodData#10]
I was able to get a .xls file along with the .json whenever I ran the stock transactions option yet now can't get a .xls file created.

**Comment by arungeorge101** [comment]
Are you seeing any error on the command line? If yes can you please send me the error?
I did update the version to use python3. So make sure you are using python3.

**Comment by BerkhanEminsoy** [comment]
Yep using python 3 ...
![Screenshot (22)](https://user-images.githubusercontent.com/9651199/109640571-b7c33580-7b61-11eb-9cfe-3b07c6e8fe68.png)

**Comment by arungeorge101** [comment]
Sorry been busy, but I just tested this and the stock transactions xls file is getting generated. Depending on the number of your transaction it will take some time to generate the file. My file was about 216Kb and around 1300Line items and it took about 5-6 minutes to complete.
