### ISSUE TITLE
Dates getting copied incorrectly

### ISSUE THREAD

**Issue by BerkhanEminsoy** [arungeorge101/myRobinhoodData#11]
This might be a timezone issue but the dates are getting copied incorrectly into the .xls sheet. Not sure why but they are off by 1-2 days.

**Comment by arungeorge101** [comment]
The date that I am showing in the excel sheet is the settlement date, which may not be the same date on which you initiated the transaction. Hence the difference of 1-2 days, there is another issue open for this https://github.com/arungeorge101/myRobinhoodData/issues/14 and I will fix it.
