### ISSUE TITLE
Use Execution Date Rather than Settlement Date for Tax Purposes

### ISSUE THREAD

**Issue by MarkIllich** [arungeorge101/myRobinhoodData#14]
In rh_data_collector.py

            stock.date = order_entry["executions"][0]["settlement_date"]
Changed to:

            # stock.date = order_entry["executions"][0]["settlement_date"]
            stock.date = order_entry["last_transaction_at"]
This should correspond to the last trade date and time if a series of partial fills needed to be done. Since this is also when you'd be able to get the correct average price and total quantity, I used it instead of the earliest execution date.

**Comment by arungeorge101** [comment]
This issue is now fixed.  Thank you for the feedback.
