### ISSUE TITLE
Cancelled and Failed Orders Being Processed and Failing

### ISSUE THREAD

**Issue by MarkIllich** [arungeorge101/myRobinhoodData#15]
This test is failing to skip "cancelled" stock orders and "failed" orders need to also be skipped.

if order_entry["state"] not in ["cancelled", "confirmed", "rejected"]:

I changed it to ...

exclude_from_list = ["cancelled", "confirmed", "rejected", "failed"]

    if order_entry["state"] not in exclude_from_list:

To resolve the issue.

**Comment by arungeorge101** [comment]
Thank you so much once again, I didnt have a failed transaction in my data yet. I have updated the code based on the above comment!
