### ISSUE TITLE
Error Exporting Options Transactions

### ISSUE THREAD

**Issue by khsykes** [arungeorge101/myRobinhoodData#19]
Exporting option transactions...
Traceback (most recent call last):
  File "src/main.py", line 24, in <module>
    robinhood.export_options_data()
  File "C:\---\myRobinhoodData-master\src\rh_data_collector.py", line 95, in export_options_data
    option.date = option_entry["legs"][0]["executions"][0]["settlement_date"]
IndexError: list index out of range

**Comment by arungeorge101** [comment]
Hi right now I am excluding all options transactions which are in this state (cancelled, confirmed or rejected). The idea being to populate only filled/completed transactions. But in your case am assuming another state that I have missed which is causing the error. You should still see a options.json file in your results folder. If you can go through and let me know the different status that you see. If you see anything other than cancelled, confirmed, rejected and filled - please let me know so I can update it.

`"state": "filled"`

**Comment by arungeorge101** [comment]
https://github.com/arungeorge101/myRobinhoodData/issues/15 

Mark pointed out a new state "failed" which I had missed. I have updated the code.
