### ISSUE TITLE
Feature Request: Extract Watchlists

### ISSUE THREAD

**Issue by rajsinghUSA** [arungeorge101/myRobinhoodData#2]
First of all, this is a great script you've written, thank you for posting it for everyone to use!

I was wondering if you could also include a feature to extract the watchlists, which happens to be the goal that led me to your script initially.

Thanks again for your nice work here.

**Comment by arungeorge101** [comment]
Thank you @rajsinghUSA 

So are you looking for all the stocks in the watchlist with their current prices? Any other information that you are looking for specifically?

**Comment by rajsinghUSA** [comment]
Actually, I was trying to export all my watchlists into the ThinkorSwim platform, which just needs a comma-separated list of ticker symbols. So if there could be separate files for each watchlist then that would be awesome.

**Comment by arungeorge101** [comment]
okay, I will add it to my to-do list. Will work on it when I find some time and will provide an update here.

**Comment by arungeorge101** [comment]
@rajsinghUSA I have added a new file getWatchlist.py. 
Copy your auth token and run this file and it should generate an excel watchlistdata.xls, with all the stocks that are in your watchlist along with the date it was added.

**Comment by thapar** [comment]
You are amazing, thank you!!
