### ISSUE TITLE
Requuirementx.txt needs update

### ISSUE THREAD

**Issue by nitimish475** [arungeorge101/myRobinhoodData#7]
Changed these two and runtime error resolved  for command  - pip install -r requirements.txt

numpy==1.16.6  to be changed to 1.19.1
pandas==0.24.2 to pandas-1.1.1

Getting some other error as compatibility -

ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

robinhood 1.0.1 requires requests<=2.18.4,>=2.13.0, but you'll have requests 2.23.0 which is incompatible.
robinhood 1.0.1 requires six<=1.11.0,>=1.10.0, but you'll have six 1.14.0 which is incompatible.

**Comment by arungeorge101** [comment]
The requirements.txt has been updated. Please run the latest code and let me know if you see issues.
